[project]
name = "Capitals"
version = "0.1.0"
description = "State capitals data module"
requires-python = ">=3.12"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["Capitals"]